# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfea6c87383c90f5519916e175b6a86742f91c2b69887a83617253d8e6981f2343994ce837bd8248040e27ee68c9fc0f1d60a5ca1c8ec47cd6809d7342c1d0b7

test:
  secret_key_base: e9746142ece0745f6040b49a7397bf9060075c2a7dd2f02c77ea0e8bc9e3d77880a524a8223346a2d31dfdd50e8652a2d9eea2418532d30b2f120d8996c75745

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
